<!DOCTYPE html>
<html lang="en">

<head>
<?php include 'header.inc'; ?>
</head>

<body>
<?php include 'menu.inc'; ?>

<div class="fieldset">
    <section id="enhance">
    <h2>Enhancements</h2>
    <ol>
    <li><strong>Add questions in the “quizs” table in the DB and have dynamic HTML generated by PHP</strong>: 
    <ul>
        <li>Create a form to add questions on supervisors' side</li>
        <li>Enter information such as question content, answers, correct answers, points, display order, question type</li>
        <li>When you click “Save”, the question will be saved in the “quizs” table in the DB</li>
        <li>At the quiz.php screen, PHP will use PHP to process the question and answer view by processing and inserting html codes for it so that it generates the correct html code to suit each type of question.</li>
    </ul>
    <li><strong>Create a table to save supervisors' information and login</strong>:
    <ul>
        <li>Create a table of “supervisors” including information such as id, username, password</li>
        <li>Supervisors only work with the system when logging in with the correct username and password</li>
        <li>When entered incorrectly, a counter variable will be incremented by 1. If entered incorrectly 3 times, an error message will be displayed with a message waiting for login after 5 minutes</li>
        <li>After 5 minutes, supervisors must enter the correct username vs password to be able to log back into the system and the counter will be reset = 0</li>
    </ul>
    <li><strong>Supervisors can change the order in which questions are displayed</strong>:
    <ul>
        <li>Supervisors log into the system and open the list of questions</li>
        <li>Supervisors select the question to change the order (smaller order will be displayed at the top)</li>
    </ul>
</ol>
    </section>
</div>
<footer>
<?php include 'footer.inc'; ?>
</footer>
</body>
</html>