<meta charset="utf-8" />
  <meta name="description" content="VoiceXML"/>
  <meta name="keywords"    content="HTML, CSS, JavaScript"/>
  <meta name="author"      content="Dat Pham"/>
  <title>Voice XML</title>
  <link href="styles/style.css" rel="stylesheet"/>
  <link href="styles/responsive.css" rel="stylesheet"/>
  <script  src="scripts/quiz.js"></script>
  <script src = "scripts/enhancements.js"></script>    
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>