  <header>
     <h1>VoiceXML</h1>
     <nav>
       <ul class="navbar"> 
         <li><a href="index.php">Home</a></li>
           <li><a href="topic1.php">VoiceXML editor</a>
             <ul class="small_navbar">
               <li><a href="topic1.php">VoiceXML definitions</a>
                 <ul class="small_navbar2">
                   <li><a href="topic1.php#WIV">What is VoiceXML?</a></li>
                   <li><a href="topic1.php#WIE">What is ECMAScript?</a></li>
                   <li><a href="topic1.php#JSP">JavaServer Pages</a></li>
                 </ul>
               </li>
               <li><a href="topic2.php">VoiceXML editor features</a>
                 <ul class="small_navbar2">
                   <li><a href="topic2.php#CCE">Color coding editor</a></li>
                   <li><a href="topic2.php#VCT">VoiceXML coding tips</a></li>
                   <li><a href="topic2.php#CA">Content Assist</a></li>
                 </ul>
               </li>
             </ul>
           </li>
           <li><a href="quiz.php">Quiz</a></li>
           <li><a href="enhancements.php">Enhancements</a>
             <ul class="small_navbar">
               <li><a href="enhancements.php">CSS</a></li>
               <li><a href="enhancements2.php">JavaScript</a></li>
               <li><a href="enhancements3.php">PHP</a></li>
             </li>
            </ul>
      </nav>
</header>